version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=Postgres1098!
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf
    command: ["postgrest", "/etc/postgrest.conf"]
    restart: unless-stopped

  debug:
    image: ubuntu:latest
    container_name: debug
    command: >
      bash -c "set -e &&
               apt-get update  &&
               apt-get install -y curl wget dnsutils iputils-ping netcat-openbsd postgresql-client jq  &&
               tail -f /dev/null"
volumes:
  postgres_data:
    driver: local
